### PR TITLE
Bumps dependencies, moves to AndroidX

### PR DESCRIPTION
**Pull request by ened**
Bumps various dependencies, tests still pass.

### CODE REVIEW

**Comment by karczews** [comment]
The reason why I didnt move to androidX initially was to support projects that didn't switch as well. It easy to use non-androidX project in androidX enabled ones with use of jetifier but it quite hard the other way around. 
That said I guess there is no need to support old project anymore so we can switch.

**Comment by ened** [comment]
Pretty much - AndroidX is here. :)

**Comment by ened** [comment]
Just noticed there are some IDE files in the commit.. removed & now ready to be merged.

**Comment by ened** [comment]
@karczews can you push a new release to maven?

**Pull request merged**
